FORMAT: 1A

# Login Api

The login api of adibioshop.

# 查询最顶端订单 [/dologin]

## POST

+ Request (text/html)

    + Body

            {
                username: 'admin',
                password: 'admin'
            }

+ Response 200 (application/json)

    + Body

            {
                result: "ok",
                errMsg: "",
                parm:
            }