FORMAT: 1A

# Orders Api

The orders api of adibioshop.

# 查询最顶端订单 [/latest_orders]

## GET

+ Request (text/html)

    + Body

            limit = 20(需要一次请求的数量)
            status = 'ALL'(全部), 'UNPAID'(未支付), 'PROCESSING'(处理中), 'FINISHED'(已完成), 'CANCELED'(已取消)

+ Response 200 (application/json)

    + Body

            {
                result: "ok",
                errMsg: "",
                parm: [
                    {
                        row_id: 204,
                        order_id: "374959293436264448",
                        customer_id: "60df649c-51c8-4d1d-b02c-47d44d4b7355",
                        price: 0.02,
                        status: "PAID",
                        description: null
                    },
                    {
                        row_id: 185,
                        order_id: "360093731321282560",
                        customer_id: "de14cd03-2f57-4efd-a14b-8e2cebb7a890",
                        price: 0.06,
                        status: "CANCELED",
                        description: null
                    }
                ]
            }

# 查询中间订单 [/part_orders]

## GET

+ Request (text/html)

    + Body

            limit = 20(需要一次请求的数量)
            status = 'ALL'(全部), 'UNPAID'(未支付), 'PROCESSING'(处理中), 'FINISHED'(已完成), 'CANCELED'(已取消)
            start_row = 185

+ Response 200 (application/json)

    + Body

            {
                result: "ok",
                errMsg: "",
                parm: [
                    {
                        row_id: 204,
                        order_id: "374959293436264448",
                        customer_id: "60df649c-51c8-4d1d-b02c-47d44d4b7355",
                        price: 0.02,
                        status: "PAID",
                        description: null
                    },
                    {
                        row_id: 185,
                        order_id: "360093731321282560",
                        customer_id: "de14cd03-2f57-4efd-a14b-8e2cebb7a890",
                        price: 0.06,
                        status: "CANCELED",
                        description: null
                    }
                ]
            }


# 查询订单细节 [/order_detail]

## GET

+ Request (text/html)

    + Body

            order_id = 355894887377272832

+ Response 200 (application/json)

    + Body

            {
                result: "ok",
                errMsg: "",
                parm: {
                events: [
                    {
                        order_eventid: "b5fcfc92-e5c3-45aa-94de-2656f83e1160",
                        order_id: "359430955951194112",
                        event_time: 1505736618000,
                        event_title: "CREATION",
                        event_executor: "de14cd03-2f57-4efd-a14b-8e2cebb7a890",
                        description: null
                    }
                ],
                infos: [
                    {
                        order_id: "359430955951194112",
                        order_itemid: "91882164-fcb8-4ef0-bf8a-e345c3a1e681",
                        order_infoid: "013dfc99-5691-40bd-a3b8-8fbb77ac1cbe",
                        product_id: "83f7c071-7858-4e3f-b000-3c011db15e41",
                        product_name: "肾病早期筛查",
                        unit_price: 0.03,
                        patient_infoid: "a80e56ea-7a21-4a2e-ac56-836416d0e77b",
                        name: "周",
                        gender: "M",
                        age: 20,
                        country: "CHINA",
                        province: "北京",
                        city: "北京市",
                        district: "东城区",
                        address: "哈哈",
                        phone: "15602980405",
                        has_diabetic: 0,
                        height: 0,
                        weight: 0
                    },
                    {
                        order_id: "359430955951194112",
                        order_itemid: "7a0c32b9-568a-4a48-8520-78ebbd85ceea",
                        order_infoid: "0201c6ef-fb4f-4f47-9c35-762310ba92bd",
                        product_id: "bda342a2-27c0-4cb1-bed3-11a786391365",
                        product_name: "糖尿病早期筛查",
                        unit_price: 0.03,
                        patient_infoid: "a80e56ea-7a21-4a2e-ac56-836416d0e77b",
                        name: "周",
                        gender: "M",
                        age: 20,
                        country: "CHINA",
                        province: "北京",
                        city: "北京市",
                        district: "东城区",
                        address: "哈哈",
                        phone: "15602980405",
                        has_diabetic: 0,
                        height: 0,
                        weight: 0
                    }
                ],
                order: {
                    row_id: 0,
                    order_id: "359430955951194112",
                    customer_id: "de14cd03-2f57-4efd-a14b-8e2cebb7a890",
                    price: 0.06,
                    status: "CANCELED",
                    description: null
                    }
                }
            }
