FORMAT: 1A

# Orders Api

The orders api of adibioshop.

# 查询最顶端订单 [/latest_orders]

## GET

+ Request (text/html)

    + Body

            limit = 20(需要一次请求的数量)
            status = 'ALL'(全部), 'UNPAID'(未支付), 'PROCESSING'(处理中), 'FINISHED'(已完成), 'CANCELED'(已取消)

+ Response 200 (application/json)

    + Body

            {
                result: "ok",
                errMsg: "",
                parm: [
                    {
                        row_id: 204,
                        order_id: "374959293436264448",
                        customer_id: "60df649c-51c8-4d1d-b02c-47d44d4b7355",
                        price: 0.02,
                        status: "PAID",
                        description: null
                    },
                    {
                        row_id: 185,
                        order_id: "360093731321282560",
                        customer_id: "de14cd03-2f57-4efd-a14b-8e2cebb7a890",
                        price: 0.06,
                        status: "CANCELED",
                        description: null
                    }
                ]
            }

# 查询中间订单 [/part_orders]

## GET

+ Request (text/html)

    + Body

            limit = 20(需要一次请求的数量)
            status = 'ALL'(全部), 'UNPAID'(未支付), 'PROCESSING'(处理中), 'FINISHED'(已完成), 'CANCELED'(已取消)
            start_row = 185

+ Response 200 (application/json)

    + Body

            {
                result: "ok",
                errMsg: "",
                parm: [
                    {
                        row_id: 204,
                        order_id: "374959293436264448",
                        customer_id: "60df649c-51c8-4d1d-b02c-47d44d4b7355",
                        price: 0.02,
                        status: "PAID",
                        description: null
                    },
                    {
                        row_id: 185,
                        order_id: "360093731321282560",
                        customer_id: "de14cd03-2f57-4efd-a14b-8e2cebb7a890",
                        price: 0.06,
                        status: "CANCELED",
                        description: null
                    }
                ]
            }


# 查询订单细节 [/order_detail]

## GET

+ Request (text/html)

    + Body

            order_id = 355894887377272832

+ Response 200 (application/json)

    + Body

            {
                result: "ok",
                errMsg: "",
                parm: {
                    wechat: {
                        customer_id: "ae05c099-96a2--8763-165db088ab6b",
                        openid: "owNVIwdLGp07zeIZTFDPak8",
                        nickname: "张三",
                        sex: "1",
                        province: "广东",
                        city: "深圳",
                        headimgurl: "http://wx.qlogo.cn/mmopen/vi_32//0"
                    },
                    events: [
                        {
                            order_eventid: "cb8f66f4-2af7-44f9-8828-3dfcadd3009c",
                            order_id: "377144948622884864",
                            event_time: 1509959963000,
                            event_title: "CREATION",
                            event_executor: "ae05c099-96a2-458b-8763-165db088ab6b",
                            description: null
                        },
                        {
                            order_eventid: "9fd20618-c97e-4b2f-a767-907e6e35b41b",
                            order_id: "377144948622884864",
                            event_time: 1509959968000,
                            event_title: "PAID",
                            event_executor: "ae05c099-96a2-458b-8763-165db088ab6b",
                            description: null
                        }
                    ],
                    infos: [
                        {
                            order_id: "377144948622884864",
                            order_itemid: "69153849-4818-4464-acb4-82a3f39d5913",
                            order_infoid: "377144948643856384",
                            product_id: "bda342a2-27c0-4cb1-bed3-11a786391365",
                            product_name: "糖尿病早期筛查",
                            unit_price: 0.03,
                            order_patient_infoid: "a7b61a59-9872-4d9e-89ad-b10a785e2714",
                            name: "黄树华",
                            gender: "M",
                            age: 20,
                            country: "CHINA",
                            province: "北京",
                            city: "北京市",
                            district: "东城区",
                            address: "你好",
                            phone: "13723734925",
                            has_diabetic: 0,
                            height: 0,
                            weight: 0
                        }
                    ],
                    order: {
                        row_id: 0,
                        order_id: "377144948622884864",
                        customer_id: "ae05c099-963-165db088ab6b",
                        price: 0.03,
                        status: "PAID",
                        description: null
                    }
                }
            }

# 根据order_infoid查询order_id [/infoid_to_orderid]

## GET

+ Request (text/html)

    + Body

            infoid

+ Response 200 (application/json)

    + Body

            {
                result: "ok",
                errMsg: "",
                parm: {
                    order_id: "374959293436264448"
                }
            }

# 查询最新返现信息 [/latest_need_cashback]

## GET

+ Request (text/html)

    + Body

            limit

+ Response 200 (application/json)

    + Body

            {
                result: "ok",
                errMsg: "",
                parm: [
                    {
                        cashbacks: [
                            {
                                order_id: "377947792322068480",
                                order_infoid: "377947792351428608",
                                product_name: "糖尿病早期筛查",
                                unit_price: 0.03,
                                discount: 0.01,
                                cashback: 0.01
                            },
                            {
                                order_id: "377947792322068480",
                                order_infoid: "377947792376594432",
                                product_name: "肾病早期筛查",
                                unit_price: 0.03,
                                discount: 0.01,
                                cashback: 0.01
                            },
                            {
                                order_id: "377947792322068480",
                                order_infoid: "377947792384983040",
                                product_name: "肾病早期筛查",
                                unit_price: 0.03,
                                discount: 0.01,
                                cashback: 0.01
                            }
                        ],
                        share: {
                            row_id: 2,
                            share_id: "360e0a8c-f296-4910-8db8-e2c5c68da900",
                            from_id: "f668fe1a-372e-4bf2-9415-3d0fca5a5688",
                            order_id: "377947792322068480",
                            _paid: false
                        },
                        whole_cashback: 0.03,
                            customer: {
                            customer_id: "f668fe1a-372e-4bf2-9415-3d0fca5a5688",
                            telphone: null,
                            email: null,
                            openid: null,
                            register_time: 1509449574000,
                            zhifubao_account: "",
                            bank_card_number: ""
                            }
                        },
                        {
                        cashbacks: [
                            {
                            order_id: "377498641708875776",
                            order_infoid: "377498641717264384",
                            product_name: "糖尿病早期筛查",
                            unit_price: 0.03,
                            discount: 0.01,
                            cashback: 0.01
                            }
                        ],
                        share: {
                            row_id: 1,
                            share_id: "ab70d930-c42e-456b-9ef5-b6de53c794db",
                            from_id: "f668fe1a-372e-4bf2-9415-3d0fca5a5688",
                            order_id: "377498641708875776",
                            _paid: false
                        },
                        whole_cashback: 0.01,
                        customer: {
                            customer_id: "f668fe1a-372e-4bf2-9415-3d0fca5a5688",
                            telphone: null,
                            email: null,
                            openid: null,
                            register_time: 1509449574000,
                            zhifubao_account: "",
                            bank_card_number: ""
                        }
                    }
                ]
            }

# 查询部分返现信息 [/part_need_cashback]

## GET

+ Request (text/html)

    + Body

            limit
            start_row
            paid = true, false

+ Response 200 (application/json)

    + Body

            {
                            result: "ok",
                            errMsg: "",
                            parm: [
                                {
                                    cashbacks: [
                                        {
                                            order_id: "377947792322068480",
                                            order_infoid: "377947792351428608",
                                            product_name: "糖尿病早期筛查",
                                            unit_price: 0.03,
                                            discount: 0.01,
                                            cashback: 0.01
                                        },
                                        {
                                            order_id: "377947792322068480",
                                            order_infoid: "377947792376594432",
                                            product_name: "肾病早期筛查",
                                            unit_price: 0.03,
                                            discount: 0.01,
                                            cashback: 0.01
                                        },
                                        {
                                            order_id: "377947792322068480",
                                            order_infoid: "377947792384983040",
                                            product_name: "肾病早期筛查",
                                            unit_price: 0.03,
                                            discount: 0.01,
                                            cashback: 0.01
                                        }
                                    ],
                                    share: {
                                        row_id: 2,
                                        share_id: "360e0a8c-f296-4910-8db8-e2c5c68da900",
                                        from_id: "f668fe1a-372e-4bf2-9415-3d0fca5a5688",
                                        order_id: "377947792322068480",
                                        _paid: false
                                    },
                                    whole_cashback: 0.03,
                                        customer: {
                                        customer_id: "f668fe1a-372e-4bf2-9415-3d0fca5a5688",
                                        telphone: null,
                                        email: null,
                                        openid: null,
                                        register_time: 1509449574000,
                                        zhifubao_account: "",
                                        bank_card_number: ""
                                        }
                                    },
                                    {
                                    cashbacks: [
                                        {
                                        order_id: "377498641708875776",
                                        order_infoid: "377498641717264384",
                                        product_name: "糖尿病早期筛查",
                                        unit_price: 0.03,
                                        discount: 0.01,
                                        cashback: 0.01
                                        }
                                    ],
                                    share: {
                                        row_id: 1,
                                        share_id: "ab70d930-c42e-456b-9ef5-b6de53c794db",
                                        from_id: "f668fe1a-372e-4bf2-9415-3d0fca5a5688",
                                        order_id: "377498641708875776",
                                        _paid: false
                                    },
                                    whole_cashback: 0.01,
                                    customer: {
                                        customer_id: "f668fe1a-372e-4bf2-9415-3d0fca5a5688",
                                        telphone: null,
                                        email: null,
                                        openid: null,
                                        register_time: 1509449574000,
                                        zhifubao_account: "",
                                        bank_card_number: ""
                                    }
                                }
                            ]
                        }

# 将返现状态改为已返现 [/paid_cashback]

## GET

+ Request (text/html)

    + Body

            share_id
            paid = true, false

+ Response 200 (application/json)

    + Body

            {
                result: "ok",
                errMsg: "",
                parm: null
            }

# 更新已形成订单的检测人信息 [/update_order_patient]

## POST

+ Request (application/json)

    + Body
            {
                order_infoid: '',           # 可以不要
                order_patient_infoid: '',   # 必须
                name: '',
                gender: '',
                age: '',
                country: '',
                province: '',
                city: '',
                district: '',
                address: '',
                phone: '',
                has_diabetic: '',
                is_pregnant = #{is_pregnant},
                height: '',
                weight: ''
            }

+ Response 200 (application/json)

    + Body

            {
                result: "ok",
                errMsg: "",
                parm: {
                          order_infoid: '',
                          order_patient_infoid: '',
                          name: '',
                          gender: '',
                          age: '',
                          country: '',
                          province: '',
                          city: '',
                          district: '',
                          address: '',
                          phone: '',
                          has_diabetic: '',
                          is_pregnant = #{is_pregnant},
                          height: '',
                          weight: ''
                      }
            }
