FORMAT: 1A

# Product Api

The product api of adibioshop.

# 查询全部产品分组 [/product_groups]

## GET

+ Request (text/html)

    + Body

+ Response 200 (application/json)

    + Body

            {
                result: "ok",
                errMsg: "",
                parm: [
                    {
                    product_groupid: "1",
                    name: "default",
                    description: null
                    }
                ]
            }

# 修改某个产品分组 [/update_product_group]

## POST

+ Request (text/html)

    + Body

+ Response 200 (application/json)

    + Body

            {
                result: "ok",
                errMsg: "",
                parm: [
                    {
                    product_groupid: "1",
                    name: "default",
                    description: null
                    }
                ]
            }

# 增加产品分组 [/add_product_group]

## POST

+ Request (text/html)

    + Body

            {
                name: 'hello',
                description: ''
            }

+ Response 200 (application/json)

    + Body

            {
                result: "ok",
                errMsg: "",
                parm: ""
            }

# 修改产品分组 [/update_product_group]

## POST

+ Request (text/html)

    + Body

            {
                product_groupid: '123445667'
                name: 'hello',
                description: ''
            }

+ Response 200 (application/json)

    + Body

            {
                result: "ok",
                errMsg: "",
                parm: ""
            }

# 删除产品分组 [/delete_product_group]

## POST

+ Request (text/html)

    + Body

            {
                product_groupid: '123445667'
            }

+ Response 200 (application/json)

    + Body

            {
                result: "ok",
                errMsg: "",
                parm: ""
            }

# 查询一个分组里的所有产品 [/product_list]

## GET

+ Request (text/html)

    + Body

            product_groupid=1

+ Response 200 (application/json)

    + Body

            {
                result: "ok",
                errMsg: "",
                parm: [
                    {
                        product_id: "bda342a2-27c0-4cb1-bed3-11a786391365",
                        product_groupid: "1",
                        product_name: "糖尿病早期筛查",
                        unit_price: 0.03,
                        description: null
                    },
                    {
                        product_id: "83f7c071-7858-4e3f-b000-3c011db15e41",
                        product_groupid: "1",
                        product_name: "肾病早期筛查",
                        unit_price: 0.03,
                        description: null
                    },
                    {
                        product_id: "27e21552-3127-4b9d-8c79-6c791a22b3ec",
                        product_groupid: "1",
                        product_name: "中风早期筛查",
                        unit_price: 0.03,
                        description: null
                    }
                ]
            }

# 查询一个产品下的所有优惠信息[/product_discount_list]

## GET

+ Request (text/html)

    + Body
            product_id
+ Response 200 (application/json)

    + Body
            {
                product_discount_id: ''
                product_id: ''
                discount_type: ''
                discount: ''
                cashback: ''
                description: ''
            }

# 修改产品信息 [/update_product]

## POST

+ Request (text/html)

    + Body

            {
                product_id: '123445667'
                name: 'hello',
                description: ''
            }

+ Response 200 (application/json)

    + Body

            {
                result: "ok",
                errMsg: "",
                parm: ""
            }

# 修改产品优惠信息 [/update_product_discount]

## POST

+ Request (text/html)

    + Body

            {
                product_discount_id: "",
                product_id: "",
                discount_type: "",
                discount: "",
                cashback: "",
                description: "",
            }

+ Response 200 (application/json)

    + Body

            {
                result: "ok",
                errMsg: "",
                parm: ""
            }
